print("Nabos Jeremy Albis")
print("Mercado, Boac, Marinduque")
print("October 3, 2001")
print("Marinduque State College")
print("BSIT")
print("2-D")
print("Reading novels")
print("Playing online games")
print("Reading mangas")
print("Watching anime")
print("Working out")